package resources

const (
	HAMR_PLACE_CODE_BRANIK = "171"
	HAMR_PLACE_CODE_ZABEHLICE = "169"
	HAMR_PLACE_CODE_STERBOHOLY = "172"

	HAMR_SPORT_CODE_BEACH_VOLLEY = "149"
	HAMR_SPORT_CODE_TABLE_TENNIS = "150"
	HAMR_SPORT_CODE_SQUASH = "138"
	HAMR_SPORT_CODE_TENIS = "137"
	HAMR_SPORT_CODE_BADMINTON = "140"
	HAMR_SPORT_CODE_FLORBAL = "144"
	HAMR_SPORT_CODE_FOOTBALL = "142"

	TIME_FORMAT    = "2006-01-02"
	SEARCHES_STORE = "searches.json"
	EMAIL_CONF_STORE = "email.json"


)

const (
	SESSION_FOCUS_CHANGE_TYPE_PLACE = iota
	SESSION_FOCUS_CHANGE_TYPE_SPORT
)
